### ISSUE TITLE
[REVIEW]: SyntaxWarning in `plot_ml_vs_it.py` at lines 188 and 192

### ISSUE THREAD

**Issue by pitmonticone** [brainets/hoi#70]
When running the example script `examples/tutorials/plot_ml_vs_it.py` I encountered the following warning at lines 188 and 192:

```console
SyntaxWarning: invalid escape sequence '\p` plt.ylabel("$\partial \Omega_{[X_{1}, ..., X_{N}]}$ [Bits]")
```

REVIEW ISSUE: https://github.com/openjournals/joss-reviews/issues/7360

**Comment by EtienneCmb** [comment]
Hi @pitmonticone,

Thank you for reporting this warning. This is probably due to the use of LateX with matplotlib. Unfortunately, I can't reproduce this behavior on my machine (Linux). And the [online](https://brainets.github.io/hoi/auto_examples/tutorials/plot_ml_vs_it.html#sphx-glr-auto-examples-tutorials-plot-ml-vs-it-py) example doesn't show this warning either. 

Could you please try to update matplotlib `pip install -U matplotlib`? What's your OS?

**Comment by pitmonticone** [comment]
I have updated `matplotlib`, but the SyntaxWarning remains. 

I'm running it on macOS.

**Comment by pitmonticone** [comment]
Please consider using raw strings: 

```python
plt.ylabel(r"$\partial \Omega_{[X_{1}, ..., X_{N}]}$ [Bits]")
```

or double backslash: 

```python 
plt.ylabel("$\\partial \Omega_{[X_{1}, ..., X_{N}]}$ [Bits]")
```

**Comment by EtienneCmb** [comment]
At the top of the script, there's the line `plt.style.use('ggplot')`. Could you please try to comment this line and run the script again?

**Comment by pitmonticone** [comment]
Same output.

**Comment by pitmonticone** [comment]
Could you please publish the new version on pypi?

**Comment by pitmonticone** [comment]
Yes, now the warning is solved.

**Comment by EtienneCmb** [comment]
> Could you please publish the new version on pypi?

Version [0.0.3](https://pypi.org/project/hoi/) is on pypi
